# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b3d505e50570bf8f44099086aec839a4"
application_url = "https://automation.omni-sync.com"
embedded = true
name = "Airo Automations"
handle = "airo-automations-1"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "teststore-10010101001010716.myshopify.com"

[webhooks]
api_version = "2025-10"

  # Product webhooks for automation triggers
  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/shopify-automation"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/shopify-automation"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/shopify-automation"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "read_assigned_fulfillment_orders,read_checkouts,read_content,read_draft_orders,read_files,read_fulfillments,read_inventory,read_locales,read_locations,read_markets,read_online_store_navigation,read_online_store_pages,read_orders,read_product_listings,read_themes,read_third_party_fulfillment_orders,read_translations,unauthenticated_read_content,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,write_assigned_fulfillment_orders,write_content,write_draft_orders,write_files,write_fulfillments,write_locales,write_markets,write_orders,write_products,write_themes,write_third_party_fulfillment_orders,write_translations,write_inventory"


[auth]
redirect_urls = [
  "https://automation.omni-sync.com/authenticate",
  "https://primary-production-d49a.up.railway.app/rest/oauth2-credential/callback"
]

[pos]
embedded = false
